/***********************************************************************/
/*                                                                     */
/*  FILE        :dbsct.c                                               */
/*  DATE        :Wed, Aug 02, 2006                                     */
/*  DESCRIPTION :Setting of B,R Section                                */
/*  CPU TYPE    :SH7040                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  



#pragma section $DSEC
static const struct {
    unsigned char *rom_s;       /* 初期化データセクションのROM 上の先頭アドレス */
    unsigned char *rom_e;       /* 初期化データセクションのROM 上の最終アドレス */
    unsigned char *ram_s;       /* 初期化データセクションのRAM 上の先頭アドレス */
}   DTBL[] = {
    { __sectop("D"), __secend("D"), __sectop("R") }
};

#pragma section $BSEC
static const struct {
    unsigned char *b_s;         /* 未初期化データセクションの先頭アドレス */
    unsigned char *b_e;         /* 未初期化データセクションの最終アドレス */
}   BTBL[] = {
    { __sectop("B"), __secend("B") }
};
