/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Mon, Aug 07, 2006                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :H8/                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 3
