/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Mon, Aug 07, 2006                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8/                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x420
