
TOP_DIR = ../..


all:
	make -C $(TOP_DIR)/sample/arm/lpc1114/gcc
	make -C $(TOP_DIR)/sample/arm/stm32f103/gcc
	make -C $(TOP_DIR)/sample/arm/aduc7000/gcc
	make -C $(TOP_DIR)/sample/arm/aduc7000/armcc
	make -C $(TOP_DIR)/sample/arm/lpc2000/gcc
	make -C $(TOP_DIR)/sample/arm/lpc2000/armcc
	make -C $(TOP_DIR)/sample/sh/sh7144/gcc
#	make -C $(TOP_DIR)/sample/sh/sh7262/gcc
	make -C $(TOP_DIR)/sample/mips/jelly/gcc
	make -C $(TOP_DIR)/sample/h8/h83069/gcc

# 	make -C $(TOP_DIR)/sample/sh/sh7144/shc

