
				.h8300h


				.text

				.long		__reset_handler			; ベクタ0   リセット
				.long		__kernel_vector_dmy		; ベクタ1
				.long		__kernel_vector_dmy		; ベクタ2
				.long		__kernel_vector_dmy		; ベクタ3
				.long		__kernel_vector_dmy		; ベクタ4
				.long		__kernel_vector_dmy		; ベクタ5
				.long		__kernel_vector_dmy		; ベクタ6
				.long		__kernel_vector_dmy		; ベクタ7   NMI
				.long		__kernel_vector_dmy		; ベクタ8   TRAP0
				.long		__kernel_vector_dmy		; ベクタ9   TRAP1
				.long		__kernel_vector_dmy		; ベクタ10  TRAP2
				.long		__kernel_vector_dmy		; ベクタ11  TRAP3
				.long		__kernel_vector_dmy		; ベクタ12  IRQ0
				.long		__kernel_vector_dmy		; ベクタ13
				.long		__kernel_vector_dmy		; ベクタ14
				.long		__kernel_vector_dmy		; ベクタ15
				.long		__kernel_vector_dmy		; ベクタ16
				.long		__kernel_vector_dmy		; ベクタ17
				.long		__kernel_vector_dmy		; ベクタ18
				.long		__kernel_vector_dmy		; ベクタ19
				.long		__kernel_vector_dmy		; ベクタ20
				.long		__kernel_vector_dmy		; ベクタ21
				.long		__kernel_vector_dmy		; ベクタ22
				.long		__kernel_vector_dmy		; ベクタ23
				.long		__kernel_vector_024		; ベクタ24
				.long		__kernel_vector_dmy		; ベクタ25
				.long		__kernel_vector_dmy		; ベクタ26
				.long		__kernel_vector_dmy		; ベクタ27
				.long		__kernel_vector_dmy		; ベクタ28
				.long		__kernel_vector_dmy		; ベクタ29
				.long		__kernel_vector_dmy		; ベクタ30
				.long		__kernel_vector_dmy		; ベクタ31
				.long		__kernel_vector_dmy		; ベクタ32
				.long		__kernel_vector_dmy		; ベクタ33
				.long		__kernel_vector_dmy		; ベクタ34
				.long		__kernel_vector_dmy		; ベクタ35
				.long		__kernel_vector_dmy		; ベクタ36
				.long		__kernel_vector_dmy		; ベクタ37
				.long		__kernel_vector_dmy		; ベクタ38
				.long		__kernel_vector_dmy		; ベクタ39
				.long		__kernel_vector_dmy		; ベクタ40
				.long		__kernel_vector_dmy		; ベクタ41
				.long		__kernel_vector_dmy		; ベクタ42
				.long		__kernel_vector_dmy		; ベクタ43
				.long		__kernel_vector_dmy		; ベクタ44
				.long		__kernel_vector_dmy		; ベクタ45
				.long		__kernel_vector_dmy		; ベクタ46
				.long		__kernel_vector_dmy		; ベクタ47
				.long		__kernel_vector_dmy		; ベクタ48
				.long		__kernel_vector_dmy		; ベクタ49
				.long		__kernel_vector_dmy		; ベクタ50
				.long		__kernel_vector_dmy		; ベクタ51
				.long		__kernel_vector_dmy		; ベクタ52
				.long		__kernel_vector_dmy		; ベクタ53
				.long		__kernel_vector_dmy		; ベクタ54
				.long		__kernel_vector_dmy		; ベクタ55
				.long		__kernel_vector_dmy		; ベクタ56
				.long		__kernel_vector_dmy		; ベクタ57
				.long		__kernel_vector_dmy		; ベクタ58
				.long		__kernel_vector_dmy		; ベクタ59
				.long		__kernel_vector_dmy		; ベクタ60
				.long		__kernel_vector_dmy		; ベクタ61
				.long		__kernel_vector_dmy		; ベクタ62
				.long		__kernel_vector_dmy		; ベクタ63


				.end


